// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sample.proto
#ifndef GRPC_sample_2eproto__INCLUDED
#define GRPC_sample_2eproto__INCLUDED

#include "sample.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace sample {

class SampleService final {
 public:
  static constexpr char const* service_full_name() {
    return "sample.SampleService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SampleCall(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::sample::SampleResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::SampleResponse>> AsyncSampleCall(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::SampleResponse>>(AsyncSampleCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::SampleResponse>> PrepareAsyncSampleCall(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::SampleResponse>>(PrepareAsyncSampleCallRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SampleCall(::grpc::ClientContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SampleCall(::grpc::ClientContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sample::SampleResponse>* AsyncSampleCallRaw(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sample::SampleResponse>* PrepareAsyncSampleCallRaw(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SampleCall(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::sample::SampleResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>> AsyncSampleCall(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>>(AsyncSampleCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>> PrepareAsyncSampleCall(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>>(PrepareAsyncSampleCallRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SampleCall(::grpc::ClientContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response, std::function<void(::grpc::Status)>) override;
      void SampleCall(::grpc::ClientContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>* AsyncSampleCallRaw(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sample::SampleResponse>* PrepareAsyncSampleCallRaw(::grpc::ClientContext* context, const ::sample::SampleRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SampleCall_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SampleCall(::grpc::ServerContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SampleCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SampleCall() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SampleCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SampleCall(::grpc::ServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSampleCall(::grpc::ServerContext* context, ::sample::SampleRequest* request, ::grpc::ServerAsyncResponseWriter< ::sample::SampleResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SampleCall<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SampleCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SampleCall() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::sample::SampleRequest, ::sample::SampleResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sample::SampleRequest* request, ::sample::SampleResponse* response) { return this->SampleCall(context, request, response); }));}
    void SetMessageAllocatorFor_SampleCall(
        ::grpc::MessageAllocator< ::sample::SampleRequest, ::sample::SampleResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sample::SampleRequest, ::sample::SampleResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SampleCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SampleCall(::grpc::ServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SampleCall(
      ::grpc::CallbackServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SampleCall<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SampleCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SampleCall() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SampleCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SampleCall(::grpc::ServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SampleCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SampleCall() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SampleCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SampleCall(::grpc::ServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSampleCall(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SampleCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SampleCall() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SampleCall(context, request, response); }));
    }
    ~WithRawCallbackMethod_SampleCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SampleCall(::grpc::ServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SampleCall(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SampleCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SampleCall() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sample::SampleRequest, ::sample::SampleResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sample::SampleRequest, ::sample::SampleResponse>* streamer) {
                       return this->StreamedSampleCall(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SampleCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SampleCall(::grpc::ServerContext* /*context*/, const ::sample::SampleRequest* /*request*/, ::sample::SampleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSampleCall(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sample::SampleRequest,::sample::SampleResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SampleCall<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SampleCall<Service > StreamedService;
};

}  // namespace sample


#endif  // GRPC_sample_2eproto__INCLUDED
